version: '3.1'

services:

  mysql:
    image: mysql:8.0.3
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    volumes:
    - mysql_data_container:/data/db
    - ./initdb:/docker-entrypoint-initdb.d #script sql docker
    networks:
    - keycloak_network

  redis:
    image: redis:4
    container_name: redis-rasplus
    ports:
      - "6379:6379"
    volumes:
      - redis_data_container:/data/redis

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/KEYCLOAK?useSSL=false
      KC_DB_USERNAME: rasmoo
      KC_DB_PASSWORD: senha123
    command: start-dev
    depends_on:
      - mysql
    volumes:
      - keycloak_data_container:/opt/jboss/keycloak/standalone/data
    networks:
      - keycloak_network

  rabbitmq:
    image: rabbitmq:3-management # Imagem oficial com interface de gerenciamento
    container_name: rabbitmq_container
    ports:
      - "5672:5672" # Porta para conexões com clientes (AMQP)
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin # Usuário padrão
      RABBITMQ_DEFAULT_PASS: admin123 # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistência de dados

networks:
  keycloak_network:
    driver: bridge

volumes:
  mysql_data_container:
  redis_data_container:
  keycloak_data_container:
  rabbitmq_data:
